# Generated by Django 2.0.2 on 2019-07-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restname', models.CharField(max_length=200)),
                ('itemname', models.CharField(max_length=200)),
                ('quan', models.CharField(max_length=5)),
                ('price', models.CharField(max_length=5)),
                ('image', models.ImageField(upload_to='images/')),
                ('spec', models.CharField(max_length=500)),
            ],
        ),
    ]
